Update topic reward and forecast score
allora-network/allora-indexer pull request #31
Opened 2024-09-21 00:00 UTC by RedBird96

We need to create tables for topic `reward` and `forecast task score` to store all histories

2024-09-23 04:34 UTC, kpeluso commented on scripts/v5/new_tables.sql
> +    CONSTRAINT unique_topic_forecasting_scores_entry UNIQUE (topic_id, height_tx)
i've been in habit of storing bignums as string (reward + score)

2024-09-23 16:21 UTC, RedBird96 commented on scripts/v5/new_tables.sql
> +    CONSTRAINT unique_topic_forecasting_scores_entry UNIQUE (topic_id, height_tx)
Yes, good catch
Actually there are pros and cons using string. 
When using strings, the query may be slower and large storage problem then `BIGINT`.  However it can be safe for arbitrary precision numbers.

2024-09-23 16:21 UTC, RedBird96 commented on scripts/v5/new_tables.sql
> +CREATE TABLE IF NOT EXISTS topic_forecasting_scores (
yes, I will create tick for this

2024-09-24 13:40 UTC, xmariachi commented on scripts/v5/new_tables.sql
> +    CONSTRAINT unique_topic_forecasting_scores_entry UNIQUE (topic_id, height_tx)
Agree on using string, some of our values (esp rewards) can be huge.

2024-09-24 14:16 UTC, xmariachi requested changes
LGTM re logic,  but requested refactoring of migration scripts.

2024-09-24 14:16 UTC, xmariachi commented on scripts/v5/new_tables.sql
> +);
Please set these in a separate file from the `v0.5.0` migration. So we separate migrations per version. Please also rename `v5` to `v0.5.0` using the actual migration name.

Create/Rename files using timestamps at prefix (which mark the order): 
`scripts/<version>/<timestamp>_<action>_<description>.sql` 

eg 
`scripts/v0.5.0/202409201200_add_tokenomics_ema_commits_tables.sql` 
`scripts/v0.5.1/202409241600_add_topic_rewards_and_forecasts_tables.sql`

2024-09-24 18:26 UTC, xmariachi approved these changes

2024-09-24 18:30 UTC, merged